/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.polypro.view;


import com.polypro.helper.DialogHelper;
import com.polypro.helper.ShareHelper;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author admin
 */
public class MainJFrame extends javax.swing.JFrame {
    int timerun = 0;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        init();
    }
    
    void init() {
    	setIconImage(ShareHelper.APP_ICON);
        setLocationRelativeTo(null);
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");
            @Override
            public void actionPerformed(ActionEvent e) {
                lblTime.setText(format.format(new Date()));
            }
        }).start();
        this.openWelcome();
        this.openLogin();
    }

    void openLogin() {
        new DangNhapJDialog(this, true).setVisible(true);
    }

    void openWelcome() {
        new ChaoJDialog(this, true).setVisible(true);
    }
    
    void openWebsite() {
        try {
            Desktop.getDesktop().browse(new File("/help/index.html").toURI());
        } catch (IOException e) {
            DialogHelper.alert(this, "Không tìm thấy file hướng dẫn!");
        }
    }

    void logoff() {
        ShareHelper.logoff();
        this.openLogin();
    }
    
    void exit() {
        if (DialogHelper.confirm(this, "Bạn thực sự muốn kết thúc?")) {
            System.exit(0);
        }
    }
    
    void openThongKe(int index){
        if (ShareHelper.authenticated()) {
            ThongKeJFrame nh = new ThongKeJFrame(index);
            nh.setVisible(true);
            nh.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }else{
            DialogHelper.alert(this, "Vui lòng đăng nhập");
        }
    }
    
    void openNhanVien() {
        if (ShareHelper.authenticated()) {
            new NhanVienJFrame().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openKhoaHoc() {
        if (ShareHelper.authenticated()) {
            new KhoaHocJFrame().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openChuyenDe() {
        if (ShareHelper.authenticated()) {
            ChuyenDeJFrame cd = new ChuyenDeJFrame();
            cd.setVisible(true);
            cd.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openNguoiHoc() {
        if (ShareHelper.authenticated()) {
            new NguoiHocJFrame().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openAbout() {
        new GioiThieuJDialog(this, true).setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDangxuat = new javax.swing.JButton();
        btnKetthuc = new javax.swing.JButton();
        btnChuyende = new javax.swing.JButton();
        btnNguoihoc = new javax.swing.JButton();
        btnKhoahoc = new javax.swing.JButton();
        btnHuongdan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHethong = new javax.swing.JMenu();
        mniDangnhap = new javax.swing.JMenuItem();
        mniDangxuat = new javax.swing.JMenuItem();
        mniDoimatkhau = new javax.swing.JMenuItem();
        mniKetthuc = new javax.swing.JMenuItem();
        mnuQuanly = new javax.swing.JMenu();
        mniQLNguoihoc = new javax.swing.JMenuItem();
        mniQLChuyende = new javax.swing.JMenuItem();
        mniQLKhoahoc = new javax.swing.JMenuItem();
        mniQLNhanvien = new javax.swing.JMenuItem();
        mnuThongke = new javax.swing.JMenu();
        mniTKNguoihoc = new javax.swing.JMenuItem();
        mniTKBangdiem = new javax.swing.JMenuItem();
        mniDiemtungkhoa = new javax.swing.JMenuItem();
        mniDoanhthu = new javax.swing.JMenuItem();
        mnuTrogiup = new javax.swing.JMenu();
        mniHuongdan = new javax.swing.JMenuItem();
        mniGioithieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnDangxuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Log out.png"))); // NOI18N
        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.setFocusable(false);
        btnDangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangxuat.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnDangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangxuat);

        btnKetthuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKetthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Stop.png"))); // NOI18N
        btnKetthuc.setText("Kết thúc");
        btnKetthuc.setFocusable(false);
        btnKetthuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetthuc.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnKetthuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetthucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKetthuc);

        btnChuyende.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Lists.png"))); // NOI18N
        btnChuyende.setText("Chuyên đề");
        btnChuyende.setFocusable(false);
        btnChuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyende.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnChuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyendeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChuyende);

        btnNguoihoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Conference.png"))); // NOI18N
        btnNguoihoc.setText("Người học");
        btnNguoihoc.setFocusable(false);
        btnNguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoihoc.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnNguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoihocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNguoihoc);

        btnKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Certificate.png"))); // NOI18N
        btnKhoahoc.setText("Khóa học");
        btnKhoahoc.setFocusable(false);
        btnKhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoahoc.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnKhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoahocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoahoc);

        btnHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Globe.png"))); // NOI18N
        btnHuongdan.setText("Hướng dẫn");
        btnHuongdan.setFocusable(false);
        btnHuongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongdan.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnHuongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongdanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHuongdan);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Info.png"))); // NOI18N
        jLabel1.setText("Hệ thống quản lý đào tạo");

        lblTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Alarm.png"))); // NOI18N
        lblTime.setText("Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTime))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTime)))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/logo.png"))); // NOI18N

        mnuHethong.setText("Hệ thống");

        mniDangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mniDangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Key.png"))); // NOI18N
        mniDangnhap.setText("Đăng nhập");
        mniDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangnhapActionPerformed(evt);
            }
        });
        mnuHethong.add(mniDangnhap);

        mniDangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mniDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Log out.png"))); // NOI18N
        mniDangxuat.setText("Đăng xuất");
        mniDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangxuatActionPerformed(evt);
            }
        });
        mnuHethong.add(mniDangxuat);

        mniDoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Refresh.png"))); // NOI18N
        mniDoimatkhau.setText("Đổi mật khẩu");
        mnuHethong.add(mniDoimatkhau);

        mniKetthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniKetthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Stop.png"))); // NOI18N
        mniKetthuc.setText("Kết thúc");
        mniKetthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetthucActionPerformed(evt);
            }
        });
        mnuHethong.add(mniKetthuc);

        jMenuBar1.add(mnuHethong);

        mnuQuanly.setText("Quản lý");

        mniQLNguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Conference.png"))); // NOI18N
        mniQLNguoihoc.setText("Người học");
        mniQLNguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNguoihocActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniQLNguoihoc);

        mniQLChuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Lists.png"))); // NOI18N
        mniQLChuyende.setText("Chuyên đề");
        mniQLChuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLChuyendeActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniQLChuyende);

        mniQLKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Certificate.png"))); // NOI18N
        mniQLKhoahoc.setText("Khóa học");
        mnuQuanly.add(mniQLKhoahoc);

        mniQLNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/User group.png"))); // NOI18N
        mniQLNhanvien.setText("Nhân viên");
        mniQLNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNhanvienActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniQLNhanvien);

        jMenuBar1.add(mnuQuanly);

        mnuThongke.setText("Thống kê");

        mniTKNguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Clien list.png"))); // NOI18N
        mniTKNguoihoc.setText("Người học từng năm");
        mniTKNguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKNguoihocActionPerformed(evt);
            }
        });
        mnuThongke.add(mniTKNguoihoc);

        mniTKBangdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Card file.png"))); // NOI18N
        mniTKBangdiem.setText("Bảng điểm khóa học");
        mniTKBangdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKBangdiemActionPerformed(evt);
            }
        });
        mnuThongke.add(mniTKBangdiem);

        mniDiemtungkhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Bar chart.png"))); // NOI18N
        mniDiemtungkhoa.setText("Điểm từng khóa học");
        mniDiemtungkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemtungkhoaActionPerformed(evt);
            }
        });
        mnuThongke.add(mniDiemtungkhoa);

        mniDoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Dollar.png"))); // NOI18N
        mniDoanhthu.setText("Doanh thu từng chuyên đề");
        mniDoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhthuActionPerformed(evt);
            }
        });
        mnuThongke.add(mniDoanhthu);

        jMenuBar1.add(mnuThongke);

        mnuTrogiup.setText("Trợ giúp");

        mniHuongdan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Globe.png"))); // NOI18N
        mniHuongdan.setText("Hướng dẫn sử dụng");
        mniHuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuongdanActionPerformed(evt);
            }
        });
        mnuTrogiup.add(mniHuongdan);

        mniGioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Brick house.png"))); // NOI18N
        mniGioithieu.setText("Giới thiệu sản phẩm");
        mniGioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioithieuActionPerformed(evt);
            }
        });
        mnuTrogiup.add(mniGioithieu);

        jMenuBar1.add(mnuTrogiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDangnhapActionPerformed

    private void mniDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangxuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDangxuatActionPerformed

    private void mniQLNguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNguoihocActionPerformed
        // TODO add your handling code here:
        NguoiHocJFrame nh = new NguoiHocJFrame();
        nh.setVisible(true);
        nh.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mniQLNguoihocActionPerformed

    private void mniQLChuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLChuyendeActionPerformed
        // TODO add your handling code here:
        ChuyenDeJFrame cd = new ChuyenDeJFrame();
        cd.setVisible(true);
        cd.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mniQLChuyendeActionPerformed

    private void mniDoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhthuActionPerformed
        // TODO add your handling code here:
        openThongKe(3);
    }//GEN-LAST:event_mniDoanhthuActionPerformed

    private void btnKetthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetthucActionPerformed
        // TODO add your handling code here:
        
        exit();
    }//GEN-LAST:event_btnKetthucActionPerformed

    private void btnChuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyendeActionPerformed
        // TODO add your handling code here:        
        openChuyenDe();
    }//GEN-LAST:event_btnChuyendeActionPerformed

    private void mniKetthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetthucActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(this, "Bạn chắc chứ?",
                "Thoát", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (ret == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_mniKetthucActionPerformed

    private void mniQLNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNhanvienActionPerformed
        // TODO add your handling code here:
        NhanVienJFrame nv = new NhanVienJFrame();
        nv.setVisible(true);
        nv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mniQLNhanvienActionPerformed

    private void mniDiemtungkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemtungkhoaActionPerformed
        // TODO add your handling code here:
        openThongKe(2);
    }//GEN-LAST:event_mniDiemtungkhoaActionPerformed

    private void btnNguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoihocActionPerformed
        // TODO add your handling code here:
        NguoiHocJFrame nh = new NguoiHocJFrame();
        nh.setVisible(true);
        nh.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnNguoihocActionPerformed

    private void btnKhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoahocActionPerformed
        // TODO add your handling code here:
        KhoaHocJFrame tk = new KhoaHocJFrame();

        if (ShareHelper.authenticated()) {
            tk.setVisible(true);
            tk.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }//GEN-LAST:event_btnKhoahocActionPerformed

    private void mniTKNguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKNguoihocActionPerformed
        // TODO add your handling code here:
        openThongKe(0);
        
    }//GEN-LAST:event_mniTKNguoihocActionPerformed

    private void mniTKBangdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKBangdiemActionPerformed
        // TODO add your handling code here:
        openThongKe(1);
    }//GEN-LAST:event_mniTKBangdiemActionPerformed

    private void mniGioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioithieuActionPerformed
        // TODO add your handling code here:
        GioiThieuJDialog gt = new GioiThieuJDialog(this, rootPaneCheckingEnabled);
        gt.setVisible(true);
        gt.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mniGioithieuActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        // TODO add your handling code here:
        logoff();
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnHuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongdanActionPerformed
        openWebsite();
    }//GEN-LAST:event_btnHuongdanActionPerformed

    private void mniHuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuongdanActionPerformed
        openWebsite();
    }//GEN-LAST:event_mniHuongdanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyende;
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnHuongdan;
    private javax.swing.JButton btnKetthuc;
    private javax.swing.JButton btnKhoahoc;
    private javax.swing.JButton btnNguoihoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenuItem mniDangnhap;
    private javax.swing.JMenuItem mniDangxuat;
    private javax.swing.JMenuItem mniDiemtungkhoa;
    private javax.swing.JMenuItem mniDoanhthu;
    private javax.swing.JMenuItem mniDoimatkhau;
    private javax.swing.JMenuItem mniGioithieu;
    private javax.swing.JMenuItem mniHuongdan;
    private javax.swing.JMenuItem mniKetthuc;
    private javax.swing.JMenuItem mniQLChuyende;
    private javax.swing.JMenuItem mniQLKhoahoc;
    private javax.swing.JMenuItem mniQLNguoihoc;
    private javax.swing.JMenuItem mniQLNhanvien;
    private javax.swing.JMenuItem mniTKBangdiem;
    private javax.swing.JMenuItem mniTKNguoihoc;
    private javax.swing.JMenu mnuHethong;
    private javax.swing.JMenu mnuQuanly;
    private javax.swing.JMenu mnuThongke;
    private javax.swing.JMenu mnuTrogiup;
    // End of variables declaration//GEN-END:variables
}
